#ifndef WBUDY_STM32_SNAKE_DS18B20_H
#define WBUDY_STM32_SNAKE_DS18B20_H

#include "stm32f1xx.h"

#define ONE_WIRE_DATA_PIN GPIO_PIN_10
#define ONE_WIRE_DATA_PORT GPIOB
#define ONE_WIRE_DATA_HIGH HAL_GPIO_WritePin(ONE_WIRE_DATA_PORT, ONE_WIRE_DATA_PIN, GPIO_PIN_SET)
#define ONE_WIRE_DATA_LOW HAL_GPIO_WritePin(ONE_WIRE_DATA_PORT, ONE_WIRE_DATA_PIN, GPIO_PIN_RESET)
#define ONE_WIRE_DATA_READ HAL_GPIO_ReadPin(ONE_WIRE_DATA_PORT, ONE_WIRE_DATA_PIN)


double ReadTemp();
int8_t DS18B20_Start (void);
void DS18B20_Write (uint8_t data);
uint8_t DS18B20_Read (void);
void DS18B20_Init(void);

#endif //WBUDY_STM32_SNAKE_DS18B20_H
