#ifndef WBUDY_STM32_SNAKE_BUFFERSETTINGS_H
#define WBUDY_STM32_SNAKE_BUFFERSETTINGS_H

#define BUFFER_HEIGHT 32
#define BUFFER_COUNT 4
#define ST7735_SCREEN_WIDTH 128
#define ST7735_SCREEN_HEIGHT 128

#define TRANSPARENCY_COLOR 0xf81f

#endif //WBUDY_STM32_SNAKE_BUFFERSETTINGS_H
